from enum import StrEnum


class JobState(StrEnum):
    IDLE = "idle"
    JOB_STARTING = "job_starting"
    CLEANING_OLD_RUNTIME = "cleaning_old_runtime"
    LOADING_RULES = "loading_rules"
    GENERATING_PROMPT = "generating_prompt"
    PROMPT_READY = "prompt_ready"
    SENDING_TO_WORKER = "sending_to_worker"
    WORKER_OPENING_TRAE = "worker_opening_trae"
    PROMPT_SENT = "prompt_sent"
    WAITING_TRAE = "waiting_trae"
    AWAITING_CONTINUE = "awaiting_continue"
    COLLECTING_TRACE = "collecting_trace"
    TRACE_VALIDATING = "trace_validating"
    TRACE_MISSING_ABORT = "trace_missing_abort"
    SCREENSHOT_CAPTURING = "screenshot_capturing"
    PRODUCT_REVIEWING = "product_reviewing"
    BROWSER_ACCEPTING = "browser_accepting"
    GITHUB_SUBMITTING = "github_submitting"
    GITHUB_FAILED_ABORT = "github_failed_abort"
    FEISHU_PREPARING = "feishu_preparing"
    FEISHU_WRITING = "feishu_writing"
    FEISHU_FAILED_ABORT = "feishu_failed_abort"
    ROUND_COMPLETED = "round_completed"
    PROJECT_COMPLETED = "project_completed"
    STOPPED = "stopped"
    MANUAL_REQUIRED = "manual_required"
