SUPPORTED_APPS = ["Trae CN"]

WORKER_RUNTIME_VERSION = "0.1.15-interrupted-turn-recovery"

CAPABILITIES = [
    "auto_launch_trae",
    "open_trae",
    "focus_trae",
    "send_prompt",
    "trae_workspace_title_fallback",
    "trae_appactivate_foreground",
    "prompt_submission_unconfirmed_continue",
    "wait_completion",
    "trae_activity_progress",
    "trae_safe_observation_retry",
    "trae_ui_completion_detection",
    "trae_turn_completion_decision",
    "completed_trace_unavailable_handoff",
    "diagnose_ui",
    "click_continue",
    "click_confirm",
    "copy_latest_reply",
    "visual_trace_copy_button",
    "trae_local_trace_fallback",
    "capture_screenshot",
    "scan_project",
    "run_command",
    "browser_acceptance",
    "git_submit",
    "stop_current_task",
    "strict_prompt_submission_verification",
    "workspace_process_cleanup",
    "structured_stop_confirmation",
    "stop_log_noise_filter",
    "worker_command_lease_renewer",
    "cancelled_command_stop_cleanup",
    "windows_node_cmd_shims",
    "trae_delete_confirmation_cleanup",
    "project_local_npm_cache_prompt",
    "browser_acceptance_log_url_probe",
    "browser_acceptance_route_probe",
    "stop_cleanup_browser_port_listeners",
    "stop_cleanup_child_process_tree",
    "session_probe_diagnostics",
]
